/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import controller.Ctr_citas;
/**
 *
 * @author scorpion
 */
public class VwMenu extends javax.swing.JFrame implements Runnable{
    String hora, minutos, segundos, horaMenu;
    Thread hilo01;
    Thread hilo02;
    Ctr_citas cita = new Ctr_citas();

    /**
     * Creates new form VwMenu
     */
    public VwMenu() {
        initComponents();
        lbl_fecha.setText(fecha());
        hilo01 = new Thread(this);
        hilo01.start();
        hilo02 = new Thread(this);
        hilo02.start();
    }
    //En este método nos calcula la hora actual
    public void hora(){
        Calendar calendario = new GregorianCalendar();
        Date horaActual = new Date();
        
        calendario.setTime(horaActual);
        hora = calendario.get(Calendar.HOUR_OF_DAY) > 9? "" + calendario.get(Calendar.HOUR_OF_DAY): "0" + calendario.get(Calendar.HOUR_OF_DAY);
        minutos = calendario.get(Calendar.MINUTE) > 9? "" + calendario.get(Calendar.MINUTE): "0" + calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND) > 9? "" + calendario.get(Calendar.SECOND): "0" + calendario.get(Calendar.SECOND);
    }
    //En este método run se corre un hilo que se va a ejecutar todo el tiempo que esté ejecutado el código y me va a estar actualizando la hora con ayuda del método hora()
    @Override 
    public void run(){  
        Thread current = Thread.currentThread();
        while(current == hilo01){
            hora();
            lbl_hora.setText(hora+":"+minutos+":"+segundos);
            horaMenu = hora+":"+minutos+":"+segundos;
            
        }
        alertaFecha();
    }
    //Este método me ayuda a saber la fecha
    private static String fecha(){
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatofecha.format(fecha);
    }
    //Este método abre usuarios
    void openUsers(){
        VwUsers vu=new VwUsers(this, true);
        vu.setVisible(true);
    }
    //Este método me abrirá la alerta
    void openAlerta(){
        VwAlerta dlgAlerta = new VwAlerta(this, true);
        dlgAlerta.setVisible(true);
    }
    //En este método se compara la hora y fecha actual con los campos("FECHA_CITA" y "HORA_CITA") de las columnas de cita
    private void alertaFecha(){
        Thread current02 = Thread.currentThread();
        VwAlerta alerta = new VwAlerta(this, true); 
        while(current02 == hilo02){
            cita.consultarCita(horaMenu, fecha());
            if(fecha().equals(cita.objCita.getFechaCita()) && horaMenu.equals(cita.objCita.getHoraCita())){
//                alerta.setTextos(String.valueOf(cita.objCita.getIdCita()), cita.objCita.getTitulo(), cita.objCita.getDescripcion());
                openAlerta();
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_body = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_fecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_hora = new javax.swing.JLabel();
        pnl_footer = new javax.swing.JPanel();
        mbr_principal = new javax.swing.JMenuBar();
        mn_users = new javax.swing.JMenu();
        mnt_form_user = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Fecha:");

        lbl_fecha.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_fecha.setText("dd/mm/yyyy");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Hora:");

        lbl_hora.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_hora.setText("00:00:00");

        javax.swing.GroupLayout pnl_bodyLayout = new javax.swing.GroupLayout(pnl_body);
        pnl_body.setLayout(pnl_bodyLayout);
        pnl_bodyLayout.setHorizontalGroup(
            pnl_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_bodyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(pnl_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_hora)
                    .addComponent(lbl_fecha))
                .addGap(79, 79, 79))
        );
        pnl_bodyLayout.setVerticalGroup(
            pnl_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bodyLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(pnl_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_fecha))
                .addGap(35, 35, 35)
                .addGroup(pnl_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbl_hora))
                .addContainerGap(291, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_footerLayout = new javax.swing.GroupLayout(pnl_footer);
        pnl_footer.setLayout(pnl_footerLayout);
        pnl_footerLayout.setHorizontalGroup(
            pnl_footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        pnl_footerLayout.setVerticalGroup(
            pnl_footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        mn_users.setText("Usuarios");

        mnt_form_user.setText("Registro Usuarios");
        mnt_form_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnt_form_userActionPerformed(evt);
            }
        });
        mn_users.add(mnt_form_user);

        mbr_principal.add(mn_users);

        jMenu2.setText("Edit");

        jMenuItem1.setText("jMenuItem1");
        jMenu2.add(jMenuItem1);

        mbr_principal.add(jMenu2);

        jMenu1.setText("jMenu1");
        mbr_principal.add(jMenu1);

        setJMenuBar(mbr_principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_footer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnt_form_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnt_form_userActionPerformed
        // TODO add your handling code here:
        openUsers();
    }//GEN-LAST:event_mnt_form_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VwMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VwMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VwMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VwMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VwMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_hora;
    private javax.swing.JMenuBar mbr_principal;
    private javax.swing.JMenu mn_users;
    private javax.swing.JMenuItem mnt_form_user;
    private javax.swing.JPanel pnl_body;
    private javax.swing.JPanel pnl_footer;
    // End of variables declaration//GEN-END:variables
}
